version: '3.7'

services:
  cron:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-converter-xml2json
    networks:
      - default
      - public
      - smart-village-app-converter-xml2json
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-converter-xml2json
    networks:
      - default
      - public
      - smart-village-app-converter-xml2json
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.main.frontend.rule: Host:tmb.bad-belzig.smart-village.app,tmb.common.smart-village.app
        traefik.main.frontend.passHostHeader: "true"
        traefik.main.frontend.redirect.entryPoint: https
        traefik.api.frontend.rule: Host:tmb.bad-belzig.smart-village.app,tmb.common.smart-village.app
        traefik.api.frontend.passHostHeader: "true"
        traefik.api.frontend.redirect.entryPoint: https

  db:
    networks:
      smart-village-app-converter-xml2json:
        aliases:
          - smart-village-app-converter-xml2json
      adminer:
        aliases:
          - bb-bad-belzig-tmb-importer

networks:
  smart-village-app-converter-xml2json:
    external: true
  adminer:
    external: true
  public:
    external: true
